// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"http_app/pkg/mysql"
	"http_app/pkg/redis"
)

// Injectors from wire.go:

func CreateApplication() Application {
	mySQL := mysql.NewMySQL()
	redisRedis := redis.NewRedis()
	application := NewApplication(mySQL, redisRedis)
	return application
}
